### ISSUE TITLE
Who is the maintainer of this gem?

### ISSUE THREAD

**Issue by chulkilee** [richardvanhook/omniauth-salesforce#10]
On [this comment](https://github.com/richardvanhook/omniauth-salesforce/pull/9#issuecomment-17610096) @realdoug said 

> FYI, the gem is actually now being maintained here: https://github.com/realdoug/omniauth-salesforce/

Is it true? If then,
-  `gem.homepage` in gemspec should be updated
- this repository should be marked as no longer maintained blabla

And @realdoug added MIT license at https://github.com/realdoug/omniauth-salesforce/commit/7813e9496c53cdbdcb469f303e5ab335e15276b2 but I could not find whether the original author @richardvanhook had agree with that specific license (ref #4)

**Comment by realdoug** [comment]
@chulkilee I'll let @richardvanhook chime in on his thoughts on the MIT License.  I added it because Richard expressed that the code should be open source and the MIT License is in use for many salesforce related OS projects including the [databasedotcom gem](https://github.com/heroku/databasedotcom)  You make a good point about gem.homepage, I'll go ahead and make that update.  It'll be in the next time there is a release.

A note on the homepage of this repo would probably help reduce any confusion though.

**Comment by richardvanhook** [comment]
Yes, I agree with that license (MIT).

**Comment by nixme** [comment]
@richardvanhook, Would you open to a PR that changed the README to point to the newly maintained fork?

**Comment by richardvanhook** [comment]
Sure thing - link to https://github.com/realdoug/omniauth-salesforce?

**Comment by realdoug** [comment]
:+1:
